FatecLibrary.Web/Controllers/BookController.cs
using FatecLibrary.Web.Models.Entities;
using FatecLibrary.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FatecLibrary.Web.Roles;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authentication;

namespace FatecLibrary.Web.Controllers;

[Authorize(Roles = Role.Admin)]
public class BookController : Controller
{

    private readonly IBookService _bookService;
    private readonly IPublishingService _publisingService;

    public BookController(IBookService bookService, IPublishingService publisingService)
    {
        _bookService = bookService;
        _publisingService = publisingService;
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<BookViewModel>>> Index()
    {
        var result = await _bookService.GetAllBooks(await GetAccessToken());
        if (result is null) return View("Error");
        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> CreateBook()
    {
        ViewBag.PublishingId = new SelectList(
                await _publisingService.GetAllPublishers(await GetAccessToken()), "Id", "Name");

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateBook(BookViewModel bookViewModel)
    {
        if (ModelState.IsValid)
        {
            var result = await _bookService.CreateBook(bookViewModel, await GetAccessToken());

            if (result != null) return RedirectToAction(nameof(Index));
        }
        else
        {
            ViewBag.PublishingId = new SelectList(
                 await _publisingService.GetAllPublishers(await GetAccessToken()), "Id", "Name");
            // return BadRequest("Erro");
        }
        return View(bookViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> UpdateBook(int id)
    {
        ViewBag.PublishingId = new 
            SelectList(await _publisingService.GetAllPublishers(await GetAccessToken()), "Id", "Name");

        var result = await _bookService.FindBookById(id, await GetAccessToken());

        if (result is null) return View("Error");

        return View(result);
    }

    [HttpPut]
    public async Task<IActionResult> UpdateBook(BookViewModel bookViewModel)
    {
        if (ModelState.IsValid)
        {
            var result = await _bookService.UpdateBook(bookViewModel, await GetAccessToken());

            if (result is not null) return RedirectToAction(nameof(Index));

        }
        else 
            return BadRequest("Error");
        
        return View(bookViewModel);
    }

    [HttpGet]
    public async Task<ActionResult<BookViewModel>> DeleteBook(int id)
    {
        var result = await _bookService.FindBookById(id, await GetAccessToken());

        if (result is null) return View("Error");

        return View(result);
    }

    [HttpPost(), ActionName("DeleteBook")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var result = await _bookService.DeleteBookById(id, await GetAccessToken());

        if (!result) return View("Error");

        return RedirectToAction("Index");
    }
    private async Task<string> GetAccessToken()
    {
        return await HttpContext.GetTokenAsync("access_token");
    }

}

FatecLibrary.Web/Controllers/PublishingController.cs
using FatecLibrary.Web.Models.Entities;
using FatecLibrary.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FatecLibrary.Web.Roles;


namespace FatecLibrary.Web.Controllers;

[Authorize(Roles = Role.Admin)]
public class PublishingController : Controller
{

    private readonly IPublishingService _publisingService;

    public PublishingController(IPublishingService publisingService)
    {
        _publisingService = publisingService;
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<PublishingViewModel>>> Index()
    {
        var result = await _publisingService.GetAllPublishers(await GetAccessToken());
        if (result is null) return View("Error");
        return View(result);
    }

    // Criar a view CreatePublishing
    [HttpGet]
    public async Task<IActionResult> CreatePublishing()
    {
       return View();
    }
    

    [HttpPost]
    public async Task<IActionResult> CreatePublishing(PublishingViewModel publishingViewModel)
    {
        if (ModelState.IsValid)
        {
            var result = await _publisingService.CreatePublishing(publishingViewModel, await GetAccessToken());

            if (result is not null) return RedirectToAction(nameof(Index));
        }
        else
            return BadRequest("Error");
        
        return View(publishingViewModel);
    }

    // Criar a view UpdatePublishing
    [HttpGet]
    public async Task<IActionResult> UpdatePublishing(int id)
    {
        var result = await _publisingService.FindPublishingById(id, await GetAccessToken());
        if (result is null) return View("Error");
        return View(result);
    }

    [HttpPut]
    public async Task<IActionResult> UpdatePublishing(PublishingViewModel publishingViewModel)
    {
        if (ModelState.IsValid)
        {
            var result = await _publisingService.UpdatePublishing(publishingViewModel, await GetAccessToken());
            if (result is not null) return RedirectToAction(nameof(Index));
        }
        else
            return BadRequest("Error");

        return View(publishingViewModel);
    }

    // criar a view DeletePublishing
    [HttpGet]
    public async Task<ActionResult<PublishingViewModel>> DeletePublishing(int id)
    {
        var result = await _publisingService.FindPublishingById(id, await GetAccessToken());
        if (result is null) return View("Error");
        return View(result);
    }

    
    [HttpPost(), ActionName("DeletePublishing")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var result = await _publisingService.DeletePublishingById(id, await GetAccessToken());
        if (!result) return View("Error");
        return RedirectToAction("Index");
    }

    private async Task<string> GetAccessToken()
    {
        return await HttpContext.GetTokenAsync("access_token");
    }
}

FatecLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Fatec Library </title>
    <link rel="stylesheet" href="https://bootswatch.com/5/sandstone/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FatecLibrary.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Livraria da FATEC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" 
                                asp-controller="Book" asp-action="Index">Livros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" 
                                asp-controller="Publishing" asp-action="Index">Editoras</a>
                            </li>
                        }
                    </ul>
                    <!-- botao de login -->
                    <ul class="navbar-nav">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Livraria da FATEC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>